/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainView from "./module/main/MainView"
import MainCtrl from "./module/main/ctrl/MainCtrl"
import MainUiCtrl from "./module/main/ctrl/MainUiCtrl"
import MapCtrl from "./module/main/ctrl/MapCtrl"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedauto";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="scenes/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("module/main/MainView.ts",MainView);
        reg("module/main/ctrl/MainCtrl.ts",MainCtrl);
        reg("module/main/ctrl/MainUiCtrl.ts",MainUiCtrl);
        reg("module/main/ctrl/MapCtrl.ts",MapCtrl);
    }
}
GameConfig.init();